version: '3'
services:
  ring-integration:
    image: alpha-route:1.0
    restart: always
    ports:
      - "7000:7000"
    container_name: alpha-route
    volumes:
      - ../:/opt/alpah-route
      - /etc/localtime:/etc/localtime:ro
      - ../stu_gevent:/opt/alpha-route/stu_gevent

    shm_size: 16G
    command: ["/opt/alpha-route/bin/cmd.sh"]

    networks:
      - sys_dockercompose_ring-network-01

networks:
  sys_dockercompose_ring-network-01:
    external:
      name: sys_dockercompose_ring-network-01

